SELECT * FROM `CITY` WHERE `POPULATION` > 100000 AND `COUNTRYCODE` = 'USA';

SELECT `NAME` FROM `CITY` WHERE `POPULATION` > 120000 AND `COUNTRYCODE` = 'USA';

SELECT * FROM `CITY`;

SELECT * FROM `CITY` WHERE `ID` = 1661;

SELECT * FROM `CITY` WHERE `COUNTRYCODE` = 'JPN';

SELECT `NAME` FROM `CITY` WHERE `COUNTRYCODE` = 'JPN';

SELECT `CITY`, `STATE` FROM `STATION`;

SELECT DISTINCT `CITY` FROM `STATION` WHERE MOD(`ID`, 2) = 0;

SELECT COUNT(`CITY`)- COUNT(DISTINCT `CITY`) FROM `STATION`;

(SELECT `CITY`, LENGTH(`CITY`) FROM `STATION` ORDER BY LENGTH(`CITY`) ASC, `CITY` ASC LIMIT 1) UNION (SELECT `CITY`, LENGTH(`CITY`) FROM `STATION` ORDER BY LENGTH(`CITY`) DESC, `CITY` ASC LIMIT 1);

SELECT DISTINCT `CITY` FROM `STATION` WHERE SUBSTR(LOWER(`CITY`), 1, 1) IN ('a', 'e', 'i', 'o', 'u');

SELECT DISTINCT `CITY` FROM `STATION` WHERE RIGHT(LOWER(`CITY`), 1) IN ('a', 'e', 'i', 'o', 'u');

SELECT DISTINCT `CITY` FROM `STATION` WHERE `CITY` REGEXP '^[aeiou].*[aeiou]$';

SELECT DISTINCT `CITY` FROM `STATION` WHERE `CITY` NOT REGEXP '^[aeiou]';

SELECT DISTINCT `CITY` FROM `STATION` WHERE `CITY` REGEXP '[^aeiou]$';

SELECT DISTINCT `CITY` FROM `STATION` WHERE `CITY` REGEXP '^[^aeiou]|[^aeiou]$';

SELECT DISTINCT `CITY` FROM `STATION` WHERE `CITY` REGEXP '^[^aeiou].*[^aeiou]$';

SELECT `Name` FROM `STUDENTS` WHERE `Marks` > 75 ORDER BY RIGHT(`Name`, 3) ASC, `ID` ASC;

SELECT `name` FROM `Employee` ORDER BY `name` ASC;

SELECT `name` FROM `Employee` WHERE `salary` > 2000 AND `months` < 10 ORDER BY `employee_id` ASC;
